FROM bobbybabu007/jenkins:v1

# Distributed Builds plugins
RUN /usr/local/bin/install-plugins.sh ssh-slaves
RUN /usr/local/bin/install-plugins.sh gradle

# install Notifications and Publishing plugins
RUN /usr/local/bin/install-plugins.sh email-ext
RUN /usr/local/bin/install-plugins.sh mailer
RUN /usr/local/bin/install-plugins.sh slack

# Artifacts
RUN /usr/local/bin/install-plugins.sh htmlpublisher

# UI
RUN /usr/local/bin/install-plugins.sh greenballs
RUN /usr/local/bin/install-plugins.sh simple-theme-plugin

# Scaling
RUN /usr/local/bin/install-plugins.sh kubernetes

COPY plugins.txt /tmp/jenkins/plugins.txt
#RUN /usr/local/bin/install-plugins.sh $(cat /tmp/jenkins/plugins.txt)

RUN mkdir -p /usr/share/jenkins/ref/ && \
    echo lts > /usr/share/jenkins/ref/jenkins.install.UpgradeWizard.state && \
    echo lts > /usr/share/jenkins/ref/jenkins.install.InstallUtil.lastExecVersion

USER root
# Install Docker, kubectl and helm
RUN apt -qq update && \
    mkdir -p /var/lib/apt/lists/partial && \
    apt -qq -y install curl wget nano unzip python3-dev python3-setuptools python3-pip python3-yaml

#RUN curl -sSL https://get.docker.com/ | sh && \
#    curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl && \
#    chmod +x ./kubectl && \
#    mv ./kubectl /usr/local/bin/kubectl

# Install Ansible
ENV pip_packages "ansible"
RUN pip3 install --upgrade pip
RUN pip3 install $pip_packages

# Create Ansible Inventory File
RUN mkdir -p /etc/ansible && \
    echo "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts

USER jenkins
